unpackaged/main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <description>WEX Project Issue. Used to track project issues and tasks.</description>
    <label>Issue</label>
    <nameField>
        <label>Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Issue__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Issue description, to detail the steps required to implement this.</description>
    <inlineHelpText>Enter an issue description.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Issue__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>The due date of this issue.</description>
    <inlineHelpText>The due date of this issue.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Issue__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>The associated milestone for this issue.</description>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Issue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this issue.</description>
    <inlineHelpText>The status of this issue.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>WEX Project Milestone.

Used to track project milestones.</description>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Milestone__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>Milestone Due Date</description>
    <inlineHelpText>Milestone Due Date</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Milestone__c/fields/Percentage_Complete__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Complete__c</fullName>
    <description>Total Completion Percentage based on related issue records.</description>
    <formula>IF(
 Total_Number_of_Issues__c  &gt; 0,
(Total_Number_of_Completed_Issues__c / Total_Number_of_Issues__c),
0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Completion Percentage based on related issue records.</inlineHelpText>
    <label>% Complete</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The associated project for this project milestone.</description>
    <inlineHelpText>The associated project for this project milestone.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( Percentage_Complete__c  &lt;= 0, &quot;Not Started&quot;, 
   IF(Percentage_Complete__c &gt;= 1, &quot;Complete&quot;, 
      &quot;In Progress&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>WEX Project Object.

Holds top level project informaton.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>The due date, based on the max milestone due date.</description>
    <inlineHelpText>The due date, based on the max milestone due date.</inlineHelpText>
    <label>Due Date</label>
    <summarizedField>Milestone__c.Due_Date__c</summarizedField>
    <summaryForeignKey>Milestone__c.Project__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Percentage_Complete__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Complete__c</fullName>
    <description>Total Completion Percentage based on related milestone records.</description>
    <formula>IF(
    Total_Number_of_Milestones__c &gt; 0, 
    (Total_Number_of_Completed_Milestones__c / Total_Number_of_Milestones__c), 
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Completion Percentage based on related milestone records.</inlineHelpText>
    <label>% Complete</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Project status, based on the percentage complete.</description>
    <formula>IF  (Percentage_Complete__c == 0, &quot;Not Started&quot;, 
    IF(Percentage_Complete__c == 1, &quot;Complete&quot;, 
        &quot;In Progress&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Project status, based on the percentage complete.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <description>Status Picklist</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ProjectManagerController.cls
public with sharing class ProjectManagerController {
    
    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getProjectData() {
        List<Map<String, Object>> treeData = new List<Map<String, Object>>();
        List<Project__c> projects = [SELECT Id, Name, Status__c, 
                                    (SELECT Id, Name, Status__c, Due_Date__c, Percentage_Complete__c FROM Milestones__r) 
                                    FROM Project__c];
        
        Set<Id> milestoneIds = new Set<Id>();
        for (Project__c project : projects) {
            for (Milestone__c milestone : project.Milestones__r) {
                milestoneIds.add(milestone.Id);
            }
        }
        
        Map<Id, List<Issue__c>> milestoneToIssuesMap = new Map<Id, List<Issue__c>>();
        for (Issue__c issue : [SELECT Id, Name, Description__c, Milestone__c, Status__c, Due_Date__c FROM Issue__c WHERE Milestone__c IN :milestoneIds]) {
            if (!milestoneToIssuesMap.containsKey(issue.Milestone__c)) {
                milestoneToIssuesMap.put(issue.Milestone__c, new List<Issue__c>());
            }
            milestoneToIssuesMap.get(issue.Milestone__c).add(issue);
        }
        
        for (Project__c project : projects) {
            Map<String, Object> projectNode = new Map<String, Object>{
                'name' => project.Id,
                'label' => project.Name,
                'status' => project.Status__c,
                '_children' => new List<Map<String, Object>>()
            };
            for (Milestone__c milestone : project.Milestones__r) {
                Map<String, Object> milestoneNode = new Map<String, Object>{
                    'name' => milestone.Id,
                    'label' => milestone.Name,
                    'status' => milestone.Status__c,
                    'duedate' => milestone.Due_Date__c,
                    'percentage' => milestone.Percentage_Complete__c,
                    '_children' => new List<Map<String, Object>>()
                };
                // Attach Issues to Milestone
                List<Issue__c> issues = milestoneToIssuesMap.get(milestone.Id);
                if (issues != null) {
                    for (Issue__c issue : issues) {
                        Map<String, Object> issueNode = new Map<String, Object>{
                            'name' => issue.Id,
                            'label' => issue.Name,
                            'description' => issue.Description__c
                        };
                        ((List<Map<String, Object>>)milestoneNode.get('_children')).add(issueNode);
                    }
                }
                ((List<Map<String, Object>>)projectNode.get('_children')).add(milestoneNode);
            }
            treeData.add(projectNode);
        }
        system.debug(treeData);
        return treeData;
        
    }
}